# Generated by Django 5.0.6 on 2026-07-12 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('version', models.CharField(default='1.0', max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rtsp_url', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('online', 'Online'), ('pending', 'Pending'), ('offline', 'Offline')], db_index=True, default='pending', max_length=20)),
                ('last_frame_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ModelAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_assignments', to='core.camera')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.modelmeta')),
            ],
            options={
                'unique_together': {('camera', 'model')},
            },
        ),
        migrations.CreateModel(
            name='KpiRollup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window', models.CharField(choices=[('1h', '1 Hour'), ('1d', '1 Day'), ('1w', '1 Week')], max_length=5)),
                ('window_start', models.DateTimeField()),
                ('metrics', models.JSONField()),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_rollups', to='core.camera')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_rollups', to='core.modelmeta')),
            ],
            options={
                'indexes': [models.Index(fields=['camera', 'model', 'window', 'window_start'], name='core_kpirol_camera__0025b0_idx')],
                'unique_together': {('camera', 'model', 'window', 'window_start')},
            },
        ),
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('confidence', models.FloatField()),
                ('bbox', models.JSONField()),
                ('frame_reference', models.CharField(blank=True, max_length=500)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='core.camera')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='core.modelmeta')),
            ],
            options={
                'indexes': [models.Index(fields=['camera', 'timestamp'], name='core_detect_camera__fb0688_idx'), models.Index(fields=['camera', 'model', 'timestamp'], name='core_detect_camera__f5b098_idx')],
            },
        ),
    ]
